config/routes.rb
TeachboxNoit::Application.routes.draw do
  resources :quick_answers

  resources :quick_questions

  resources :comments_closed_group_posts

  resources :closed_group_posts

  resources :closed_groups

  resources :comments_course_posts

  resources :course_posts

  resources :courses

  resources :comments_open_group_posts

  resources :open_group_posts
  
  resources :searches

  resources :open_groups

  resources :random_groups

  resources :requests 

  resources :asset_opens

  root to: 'menu#index'
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users

  resources :open_groups do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
     post :like_comment, :on => :collection
     post :leave, :on => :collection
  end

 resources :closed_groups do
     post :requested, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
     post :like_comment, :on => :collection
     post :leave, :on => :collection
  end
  
  resources :courses do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
     post :like_comment, :on => :collection
     post :leave, :on => :collection
  end

  resources :requests do
    post :accept, :on => :collection
    post :decline, :on => :collection
  end

  resources :quick_questions do
    post :like_answer, :on => :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :name, :password, :attach, :pic, :description
  validates :name, :presence => true    
  validates :email, :presence => true
  validates :password, :presence => true

  has_attached_file :pic, :default_url => "/images/default.jpg"
  has_attached_file :attach

  has_many :user_open_group
  has_many :open_group_posts
  has_many :likes_open_groups
  has_many :likes_open_group_posts
  has_many :comments_open_group_posts

  has_many :user_course
  has_many :course_posts
  has_many :likes_courses
  has_many :likes_course_posts
  has_many :comments_course_posts

  has_many :user_closed_group
  has_many :closed_group_posts
  has_many :likes_closed_group
  has_many :likes_closed_group_posts
  has_many :comments_closed_group_posts

  has_many :requests
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    @userss = User.where("id = ?", params[:id])
      @userss.each do |user| 
            if current_user.present?
              if user.id == current_user.id 
                    @kartof = true
                    break
                else
                    @kartof = false 
                end
            end
        end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @userss = User.where("id = ?", params[:id])
      @userss.each do |user| 
            if current_user.present?
              if user.id == current_user.id 
                    @kartof = true
                    break
                else
                    @kartof = false 
                end
            end 
        end

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])


    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        sign_out(@user)
        sign_in(@user, :bypass => true)
        format.html { redirect_to @user}
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="topbar" style="margin-left: auto ;  margin-right: auto ;" >
<div class="left-pane"> 
          <nav>
              <%    count = 0
                    @your_opens = UserOpenGroup.all
                      @your_opens.each do |a|
                        if current_user.id == a.user_id 
                          count += 1
                        end
                    end
                  @yours_courses = UserCourse.all
                    @yours_courses.each do |b|
                      if  current_user.id == b.user_id
                        count += 1
                      end
                    end
                   @yours_closeds = UserClosedGroup.all
                    @yours_closeds.each do |c|
                      if current_user.id == c.user_id
                        count += 1
                      end
                    end   

                   if count != 0 %>
                 <ul class="side-menu" style="position: static; top: 65px; z-index: 1000; margin-top: 20px;">
                   <%= link_to({:controller => :users, :action => :show, :id => current_user.id }, { :style => "padding-left: -0px !important; "}) do %>
                      <button class="large button span_5_of_5 " style="margin-top: 0px; font-size: 16px; background-color:#2e92cf; color: white; font-weight: bold;">Твоите групи</button>
                  <% end %>
                    <% @your_opens = UserOpenGroup.all
                      @your_opens.each do |a|
                        if current_user.id == a.user_id %>
                          <li><%= link_to OpenGroup.find(a.open_group_id).name,  {:controller => :open_groups, :action => :show, :id => OpenGroup.find(a.open_group_id).id }, {:method => :get }  %>
                          </li>
                        <% end
                    end

                  @yours_courses = UserCourse.all
                    @yours_courses.each do |b|
                      if current_user.id == b.user_id %>
                         <li><%= link_to Course.find(b.course_id).name,  {:controller => :courses, :action => :show, :id => Course.find(b.course_id).id }, {:method => :get }  %>
                          </li>
                      <% end
                    end

                  @yours_closeds = UserClosedGroup.all
                    @yours_closeds.each do |c|
                      if current_user.id == c.user_id %>
                        <li> <%= link_to ClosedGroup.find(c.closed_group_id).name,  {:controller => :closed_groups, :action => :show, :id => ClosedGroup.find(c.closed_group_id).id }, {:method => :get }  %>

                         </li>
                      <% end
                    end %>
                  </ul>
                  <% end %>
                </nav>
</div>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="middle-pane"> 
<div style="width:95%; margin-top:21px; margin-left:auto; margin-right: auto; text-align: center;">
            <h2> Редакция на профил </h2>
            <table cellpadding="0" style=" border: 1px #ccc solid; width:80%; margin-left:auto; margin-right: auto; margin-top: 40px;" >
                  <tr>
                    <td  style="height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:30%; text-align:center;">
                                    <label style="color:black; font-size: 20px; margin:0; padding:0;"> Име </label>
                                    
                    </td>

                    <td  style=" height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:70%; text-align:center;">
                       <div class="input-control text" style="margin-bottom:0;">
                          <%= f.text_field :name %>
                        </div>
                      </td> 
                  </tr>
                    <tr>
                    <td  style="height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:30%; text-align:center;">
                          <label style="color:black; font-size: 20px; margin:0; padding:0;"> Парола </label>
                    </td>
                    <td  style=" height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:70%; text-align:center;">
                       <div class="input-control password" style="margin-bottom:0;">
                         <%= f.password_field :password %>
                      </div>
                      </td> 
                  </tr>
                  <tr>
                    <td  style="height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:30%; text-align:center;">
                      <label style="color:black; font-size: 20px; margin:0; padding:0;"> E-mail </label>          
                    </td>
                    <td  style=" height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:70%; text-align:center;">
                       <div class="input-control text" style="margin-bottom:0;">
                          <%= f.text_field :email %>
                        </div>
                      </td> 
                  </tr>
                  <tr>
                    <td  style="height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:30%; text-align:center;">
                                    <label style="color:black; font-size: 20px; margin:0; padding:0;"> Описание </label>
                    </td>
                    <td  style=" height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:70%; text-align:center;">
                       <div class="input-control textarea" style="margin-bottom:0;">
                        <%= f.text_area :description, :style => 'height: 100px;' %>
                       </div>
                      </td> 
                  </tr>
                  <tr>
                    <td style="height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:30%; text-align:center;">
                        <label style="color:black; font-size: 20px; margin:0; padding:5px; padding-bottom: 10px;"> Прикачете снимка </label>
                        
                    </td>
                    <td  style=" height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:70%; text-align:center;">
                        <%= f.file_field :pic, :id => "user_pic", :name => "user[pic]" %>
                      </td> 
                  </tr>
                </table>
                 <button type="submit", style="font-size: 15px; height: 35px; width:30%; background-color:#333; font-weight: bold; text-align:centefile:///C:/Users/Mapto/Desktop/TEACHBOX/edit.html#_pushr; color:white; margin-top: 20px; "> Запази промените </button>
</div>
</div>
<% end %>
<div class="right-pane"> 
       <nav>
              <ul class="side-menu" style="position: static; top: 65px; z-index: 1000;  margin-top: 19px;">

                  

                  <% 
                    questions = QuickQuestion.all
                    quickAnswers = QuickAnswer.all
                    questionCounter = 0
                    showQuest = true


                    questions.shuffle.each do |x|
                      
                      answered = false
                      
                      quickAnswers.each do |a|
                        if x.id == a.quick_question_id
                          answered = true
                        
                        end
                      end

                      if !answered 
                        if showQuest
                        %>
                        <%= link_to quick_questions_path(), :style => "padding-left: -0px !important; " do %>
                        <button class="large button span_5_of_5" style="margin-top: 0px; font-size: 16px; background-color:#2e92cf; color: white; font-weight: bold;">Неотговорени въпроси </button>
                        <% end  end%>
                        <%
                        showQuest = false
                        questionCounter += 1 %>
                        <li><%= link_to x.topic, quick_question_path(x.id) %></li>
                        <% 
                        if questionCounter == 7
                          break
                        end
                      end
                    end %>    
              </ul>
        </nav>

        <nav>
              
                <ul class="side-menu" style="position: static; top: 65px; z-index: 1000;margin-top:-1px; ">
                  <%= link_to random_groups_path, :style => "padding-left: -0px !important; " do %>
                  <button class="large button span_5_of_5" style="margin-top: 0px; font-size: 16px; background-color:#2e92cf; color: white; font-weight: bold;">Случайни групи</button>
                  <% end %>
                    <% opens = OpenGroup.all
                    limit = 0;
                    opens.shuffle.each do |x| 
                      limit = limit + 1
                      if limit == 3
                        break
                      end
                      %>
                        
                        <li>
                          <%= link_to x.name,  {:controller => :open_groups, :action => :show, :id => x.id }, {:method => :get }  %>
                        </li>
                    <% end %>
                    <% cors = Course.all
                    limit = 0;
                    cors.shuffle.each do |x| 
                      limit = limit + 1
                      if limit == 3
                        break
                      end
                      %>
                        
                        <li>
                          <%= link_to x.name,  {:controller => :courses, :action => :show, :id => x.id }, {:method => :get }  %>
                        </li>
                    <% end %>

                    <% close = ClosedGroup.all
                    limit = 0;
                    close.shuffle.each do |x| 
                      limit = limit + 1
                      if limit == 3
                        break
                      end
                      %>
                        
                        <li>
                          <%= link_to x.name,  {:controller => :closed_groups, :action => :show, :id => x.id }, {:method => :get }  %>
                        </li>
                    <% end %>
                  
                 </ul>
        </nav>
</div>
</div>

app/views/users/edit.html.erb
<% if current_user.present? && @kartof %>

<%= render 'form' %>

<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>