config/routes.rb
TeachboxNoit::Application.routes.draw do
  resources :quick_answers

  resources :quick_questions

  resources :comments_closed_group_posts

  resources :closed_group_posts

  resources :closed_groups

  resources :comments_course_posts

  resources :course_posts

  resources :courses

  resources :comments_open_group_posts

  resources :open_group_posts
  
  resources :searches

  resources :open_groups

  resources :random_groups

  resources :requests 

  resources :asset_opens

  root to: 'menu#index'
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users

  resources :open_groups do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
     post :like_comment, :on => :collection
     post :leave, :on => :collection
  end

 resources :closed_groups do
     post :requested, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
     post :like_comment, :on => :collection
     post :leave, :on => :collection
  end
  
  resources :courses do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
     post :like_comment, :on => :collection
     post :leave, :on => :collection
  end

  resources :requests do
    post :accept, :on => :collection
    post :decline, :on => :collection
  end

  resources :quick_questions do
    post :like_answer, :on => :collection
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    @course_admin = User.find(@course.user_id).name


   if @course.user_id == current_user.id
      @isAdmin = true
      
    else
      @isAdmin = false
    end
    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @closed_group }
    @users = UserCourse.where("course_id = ?", params[:id]) 
    @usersname = Array.new 
      @users.each do |user| 
        @usersname.push(User.find(user.user_id).name) 
          if current_user.present?
              if user.user_id == current_user.id 
                @pesho1 = true
                break
              else
                @pesho1 = false 
              end
          end
      end 
    if @course.user_id == current_user.id
      @admin = true
      
    else
      @admin = false
    end

    @neshto = CoursePost.where("course_id = ?", params[:id]) 
      
    @likes = LikesCourse.where("course_id = ?", params[:id]) 
    @likes.each do |user| 
        if current_user.present?
            if user.user_id == current_user.id 
              @ivan1 = true
              break
            else
              @ivan1 = false 
            end
        end
    end
end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  
  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])
    @course.user_id = current_user.id

    respond_to do |format|
      if @course.save
      	@course.save
         user_join = UserCourse.new
         user_join.user_id = current_user.id
         user_join.course_id = @course.id
         user_join.save

         user_like = LikesCourse.new
         user_like.user_id = current_user.id
         user_like.course_id = @course.id
         user_like.save

        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  def like
      # join_params = params[:user_open_group]
      like = LikesCourse.new
      like.user_id = current_user.id
      like.course_id = params[:id]
      like.save

      respond_to do |format|
        format.html { redirect_to :back }
        # format.json { head :no_content }
      end
   end
  
   def like_post
      like_post = LikesCoursePost.new
      like_post.user_id = current_user.id
      like_post.course_post_id = params[:id]
      like_post.like_attribute = params[:value]
      like_post.save

      respond_to do |format|
        format.html { redirect_to :back }
        # format.json { head :no_content }
      end
   end

   def join
      # join_params = params[:user_open_group]

      user = UserCourse.new
      user.user_id = current_user.id
      user.course_id = params[:id]
      Course.where(:id => user.course_id).update_all("counter = counter + 1")
      user.save

    respond_to do |format|
      format.html { redirect_to '/courses/'+user.course_id.to_s }
        # format.json { head :no_content }
    end
  end

  def like_comment
    like_comment = LikesCommentsCoursePost.new
    like_comment.user_id = current_user.id
    like_comment.comments_course_post_id = params[:id]
    like_comment.save

    respond_to do |format|
      format.html { redirect_to :back }
      # format.json { head :no_content }
    end
  end


   def leave
    @leave_group = UserCourse.where("user_id = ? AND course_id = ?", current_user.id,  params[:id])
    @leave_group.each do |lol| 
      lol.destroy
    end

    @leave_group = LikesCourse.where("user_id = ? AND course_id = ?", current_user.id,  params[:id])
    @leave_group.each do |lol| 
      lol.destroy
    end

    respond_to do |format|
      format.html { redirect_to :back }
      # format.json { head :no_content }
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="topbar" style="margin-left: auto ;  margin-right: auto ; " >
  <div class="left-pane" style="margin-top:10px;"> 
  <nav>
              <%    count = 0
                    @your_opens = UserOpenGroup.all
                      @your_opens.each do |a|
                        if current_user.id == a.user_id 
                          count += 1
                        end
                    end
                  @yours_courses = UserCourse.all
                    @yours_courses.each do |b|
                      if
                        count += 1
                      end
                    end
                   @yours_closeds = UserClosedGroup.all
                    @yours_closeds.each do |c|
                      if current_user.id == c.user_id
                        count += 1
                      end
                    end   

                   if count != 0 %>
                 <ul class="side-menu" style="position: static; top: 65px; z-index: 1000; margin-top: 10px;">
                  <%= link_to({:controller => :users, :action => :show, :id => current_user.id }, { :style => "padding-left: -0px !important; "}) do %>
                      <button class="large button span_5_of_5 " style="margin-top: 0px; font-size: 16px; background-color:#2e92cf; color: white; font-weight: bold;">Твоите групи</button>
                  <% end %>
                    <% @your_opens = UserOpenGroup.all
                      @your_opens.each do |a|
                        if current_user.id == a.user_id %>
                          <li><%= link_to OpenGroup.find(a.open_group_id).name,  {:controller => :open_groups, :action => :show, :id => OpenGroup.find(a.open_group_id).id }, {:method => :get }  %>
                          </li>
                        <% end
                    end

                  @yours_courses = UserCourse.all
                    @yours_courses.each do |b|
                      if current_user.id == b.user_id %>
                         <li><%= link_to Course.find(b.course_id).name,  {:controller => :courses, :action => :show, :id => Course.find(b.course_id).id }, {:method => :get }  %>
                          </li>
                      <% end
                    end

                  @yours_closeds = UserClosedGroup.all
                    @yours_closeds.each do |c|
                      if current_user.id == c.user_id %>
                        <li> <%= link_to ClosedGroup.find(c.closed_group_id).name,  {:controller => :closed_groups, :action => :show, :id => ClosedGroup.find(c.closed_group_id).id }, {:method => :get }  %>

                         </li>
                      <% end
                    end %>
                  </ul>
                  <% end %>
                </nav>
          </div>

       <div class="middle-pane"> 
      <%= form_for(@course, :html => { :name => "courseCreateForm" , :onSubmit => 'return validateCourseCreateForm();' }) do |f| %>

         <div style="width:95%; margin-top:21px; margin-left:auto; margin-right: auto; text-align: center;">
            <h2> Създаване на нов курс </h2>
            <% if @course.errors.any? %>
          <div id="error_explanation" style="text-align:center; margin-left: auto; margin-right: auto; color: red; margin-top:20px; margin-bottom: -20px;">
            <% @course.errors.full_messages.each do |msg| %>
              <li>Съществува курс с това име.</li>
            <% end %>
            </ul>
          </div>
        <% end %>
            <table cellpadding="0" style=" border: 1px #ccc solid; width:80%; margin-left:auto; margin-right: auto; margin-top: 40px;" >
                  <tr>
                    <td  style="height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:30%; text-align:center;">
                                    <label style="color:black; font-size: 20px; margin:0; padding:0;"> Име </label>
                        
                    </td>
                    <td  style=" height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:70%; text-align:center;">
                       <div class="input-control text" style="margin-bottom:0;">
                          
                          <%= f.text_field :name %>
                          <button class="btn-clear"></button>
                        </div>
                      </td> 
                  </tr>
                  <tr>
                    <td  style="height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:30%; text-align:center;">
                                    <label style="color:black; font-size: 20px; margin:0; padding:0;"> Описание </label>
                        
                    </td>
                    <td  style=" height:auto; border-bottom: 1px #ccc solid; border-right: 1px #ccc solid; width:70%; text-align:center;">
                       <div class="input-control textarea" style="margin-bottom:0;">
                         <%= f.text_area :description, :style => "height:100px;" %>
                       </div>
                      </td> 
                  </tr>
            </table>
                 <button type="submit" style="font-size: 15px; height: 35px; width:30%; background-color:#333; font-weight: bold; text-align:centefile:///C:/Users/Mapto/Desktop/TEACHBOX/edit.html#_pushr; color:white; margin-top: 20px; "> Създай курса </button>
            
        <% end %>
       </div>
       </div>

      <div class="right-pane"> 
         <nav>
              <ul class="side-menu" style="position: static; top: 65px; z-index: 1000;  margin-top: 19px;">

                  

                  <% 
                    questions = QuickQuestion.all
                    quickAnswers = QuickAnswer.all
                    questionCounter = 0
                    showQuest = true


                    questions.shuffle.each do |x|
                      
                      answered = false
                      
                      quickAnswers.each do |a|
                        if x.id == a.quick_question_id
                          answered = true
                        
                        end
                      end

                      if !answered 
                        if showQuest
                        %>
                        <%= link_to quick_questions_path(), :style => "padding-left: -0px !important; " do %>
                        <button class="large button span_5_of_5" style="margin-top: 0px; font-size: 16px; background-color:#2e92cf; color: white; font-weight: bold;">Неотговорени въпроси </button>
                        <% end  end%>
                        <%
                        showQuest = false
                        questionCounter += 1 %>
                        <li><%= link_to x.topic, quick_question_path(x.id) %></li>
                        <% 
                        if questionCounter == 7
                          break
                        end
                      end
                    end %>    
              </ul>
        </nav>

        <nav>
              
                <ul class="side-menu" style="position: static; top: 65px; z-index: 1000;margin-top:-1px; ">
                  <%= link_to random_groups_path, :style => "padding-left: -0px !important; " do %>
                  <button class="large button span_5_of_5" style="margin-top: 0px; font-size: 16px; background-color:#2e92cf; color: white; font-weight: bold;">Случайни групи</button>
                  <% end %>
                    <% opens = OpenGroup.all
                    limit = 0;
                    opens.shuffle.each do |x| 
                      limit = limit + 1
                      if limit == 3
                        break
                      end
                      %>
                        
                        <li>
                          <%= link_to x.name,  {:controller => :open_groups, :action => :show, :id => x.id }, {:method => :get }  %>
                        </li>
                    <% end %>
                    <% cors = Course.all
                    limit = 0;
                    cors.shuffle.each do |x| 
                      limit = limit + 1
                      if limit == 3
                        break
                      end
                      %>
                        
                        <li>
                          <%= link_to x.name,  {:controller => :courses, :action => :show, :id => x.id }, {:method => :get }  %>
                        </li>
                    <% end %>

                    <% close = ClosedGroup.all
                    limit = 0;
                    close.shuffle.each do |x| 
                      limit = limit + 1
                      if limit == 3
                        break
                      end
                      %>
                        
                        <li>
                          <%= link_to x.name,  {:controller => :closed_groups, :action => :show, :id => x.id }, {:method => :get }  %>
                        </li>
                    <% end %>
                  
                 </ul>
        </nav>

      </div>
 </div>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.description %></td>
    <td><%= course.name %></td>
    <td><%= course.user_id %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<%= render 'form' %>